### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by saiidabs** [k8mil/ContactCircularView#1]
Using swift 2.2 with xcode Version 7.3.1

have pod "ContactCircularView" , in the podfile, all other pods install but this

Result from terminal 
[!] Error installing ContactCircularView
[!] /usr/bin/git clone https://github.com/k8mil/ContactCircularView.git /var/folders/23/_4jw51md6875qkk7ybn4xt540000gn/T/d20161205-2950-ukjyzn --template= --single-branch --depth 1 --branch 0.1.2

Cloning into '/var/folders/23/_4jw51md6875qkk7ybn4xt540000gn/T/d20161205-2950-ukjyzn'...
warning: Could not find remote branch 0.1.2 to clone.
fatal: Remote branch 0.1.2 not found in upstream origin

**Comment by kamwysoc** [comment]
@saiidabs
Yes you're right it is something wrong with the version `0.1.0` and I have to fix it.

But If you want to use my pod for the project with swift 2.2 I highly recommend to use the 1.0.1 version.

`pod 'ContactCircularView', '~> 1.0.2' `

**Comment by saiidabs** [comment]
Sorry for the trouble , my repo was broke , all i had to do was update it.
http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/
